Repository tambo-ai/tambo, pull requests merged in 2025-03, with the labels that each got.

#66 chore(main): release hydra-ai 0.0.52
  .release-please-manifest.json
  hydra-client/CHANGELOG.md
  hydra-client/package-lock.json
  hydra-client/package.json
Labels: chore, autorelease: pending

#73 chore: Remove unused functions in react package
  react/src/providers/tambo-component-provider.tsx
  react/src/providers/tambo-thread-provider.tsx
  react/src/util/generate-component.ts
Labels: chore

#74 chore: Expose thread generation stage/status values from threadsprovider
  react/src/providers/tambo-component-provider.tsx
  react/src/providers/tambo-thread-provider.tsx
Labels: chore

#86 fix: get release-please package names right
  package-lock.json
  release-please-config.json
  showcase/package.json
Labels: fix

#88 fix: remove toolcall message from localthread during streaming
  react/src/providers/tambo-thread-provider.tsx
Labels: fix

#90 chore: let showcase have shared eslint config
  .gitignore
  package-lock.json
  showcase/eslint.config.mjs
  showcase/package.json
  showcase/src/components/ui/graph.tsx
  showcase/tsconfig.json
  turbo.json
Labels: chore

#91 chore: update release-please for monorepo setup
  .github/workflows/release-please.yml
Labels: chore

#77 chore: release main
  .release-please-manifest.json
  hydra-client/CHANGELOG.md
  hydra-client/package.json
  package-lock.json
  react/CHANGELOG.md
  react/package.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#92 fix: try separate-pull-requests per release
  .github/workflows/release-please.yml
  release-please-config.json
Labels: fix

#94 fix: typo in release_created was causing workflow to barf
  .github/workflows/release-please.yml
Labels: fix

#93 fix: avoid first message flicker
  react/src/providers/tambo-thread-provider.tsx
Labels: fix

#97 fix: no working directory necessary here
  .github/workflows/release-please.yml
Labels: fix

#95 fix: move a bunch of showcase stuff over to use SSR
  showcase/src/app/page.tsx
  showcase/src/components/footer.tsx
  showcase/src/components/second-navbar.tsx
  showcase/src/components/tab-content.tsx
  showcase/src/components/tabbed-section.tsx
  showcase/src/components/tabs/examples.tsx
  showcase/src/components/tabs/forms.tsx
  showcase/src/components/tabs/graphs.tsx
  showcase/src/components/theme-toggle.tsx
  showcase/src/components/ui/graph.tsx
  showcase/src/providers/theme-provider.tsx
Labels: fix

#99 feat: support default prod/staging urls in react client
  package-lock.json
  react/package.json
  react/src/providers/tambo-client-provider.tsx
Labels: feat

#96 chore(main): release react 0.13.0
  package-lock.json
  react/CHANGELOG.md
  react/package.json
Labels: chore, autorelease: pending

#101 fix: repo url with "npm pkg fix"
  react/package.json
Labels: fix

#102 fix: explicitly update manifest to account for separate-pull-requests: true setting
  react/.release-please-manifest.json
  react/release-please-config.json
  release-please-config.json
Labels: fix

#98 chore(main): release showcase 0.1.2
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#103 chore: force-edit the manifest
  .release-please-manifest.json
Labels: chore

#104 fix: remove excess eslint stuff from showcase
  showcase/eslint.config.mjs
Labels: fix

#106 fix: add individual release-please manifests as a test
  hydra-client/.release-please-manifest.json
  react/.release-please-manifest.json
  showcase/.release-please-manifest.json
Labels: fix

#108 fix: get rid of individual manifests, they do not work
  hydra-client/.release-please-manifest.json
  react/.release-please-manifest.json
  release-please-config.json
  showcase/.release-please-manifest.json
Labels: fix

#105 chore(main): release showcase 0.1.3
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#107 chore(main): release hydra-ai 0.0.54
  .release-please-manifest.json
  hydra-client/CHANGELOG.md
  hydra-client/package.json
Labels: chore, autorelease: pending

#100 chore(main): release react 0.13.1
  .release-please-manifest.json
  package-lock.json
  react/CHANGELOG.md
  react/package.json
Labels: chore, autorelease: pending

#110 fix: updated git repo and homepage
  react/package.json
Labels: fix

#114 fix: renaming react suffix on package (as a test)
  .github/workflows/release-please.yml
  package-lock.json
  react-sdk/README.md
  react-sdk/package.json
Labels: fix

#116 revert: "fix: renaming react suffix on package (as a test)"
  .github/workflows/release-please.yml
  package-lock.json
  react-sdk/README.md
  react-sdk/package.json
Labels: revert

#120 fix: during streaming fetch at complete
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#121 fix: bump typescript-sdk to eliminate old apis
  package-lock.json
  react-sdk/package.json
Labels: fix

#122 chore: remove referenes to hydra-client from build system
  .github/workflows/release-please.yml
  .prettierignore
  .release-please-manifest.json
  package.json
  release-please-config.json
Labels: chore

#111 chore(main): release react 0.13.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#124 fix: Send initial component state on render
  react-sdk/src/hooks/use-component-state.tsx
Labels: fix

#127 chore: bump typescript-sdk to pick up required type
  package-lock.json
  react-sdk/package.json
Labels: chore

#126 chore(main): release react 0.13.3
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#128 chore: update gif
  assets/tambo-animation.gif
Labels: chore

#139 fix: correct repo url for dependabot references/etc
  react-sdk/package.json
Labels: fix

#125 feat: add suggestionResult to useTamboSuggestions interface
  react-sdk/src/hooks/react-query-hooks.ts
  react-sdk/src/hooks/use-suggestions.ts
Labels: feat

#140 feat: bump typescript-sdk and fix react hooks lint
  package-lock.json
  react-sdk/package.json
  react-sdk/src/hooks/use-component-state.tsx
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: feat

#141 chore(main): release react 0.14.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#143 fix: include tool_call_id in response, for full round-trip
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#144 chore(main): release react 0.14.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#142 chore: fix release action to acknowledge new name (react-sdk vs react)
  .github/workflows/release-please.yml
Labels: chore

#145 fix: update showcase to be more clear
  package-lock.json
  showcase/src/app/page.tsx
  showcase/src/components/cli.tsx
  showcase/src/components/navbar.tsx
  showcase/src/components/second-navbar.tsx
  showcase/src/components/showcase-section.tsx
  showcase/src/components/showcase-sections/threads-showcase.tsx
  showcase/src/components/tab-content.tsx
  showcase/src/components/tabbed-section.tsx
  showcase/src/components/tabs/forms.tsx
  showcase/src/types/showcase.ts
  showcase/src/types/tabs.ts
Labels: fix

#146 chore: fix missing dash from release check
  .github/workflows/release-please.yml
Labels: chore

#147 chore: bump to new typescript-sdk
  package-lock.json
  react-sdk/package.json
Labels: chore

#119 feat: migration of tambo cli
  cli/README.md
  cli/eslint.config.mjs
  cli/package.json
  cli/src/cli.ts
  cli/src/commands/add/component.ts
  cli/src/commands/add/dependencies.ts
  cli/src/commands/add/index.ts
  cli/src/commands/add/tailwind.ts
  cli/src/commands/add/types.ts
  cli/src/commands/add/utils.ts
  cli/src/commands/init.ts
  cli/src/registry/chat-input/chat-input.tsx
  cli/src/registry/chat-input/config.json
  cli/src/registry/chat-input/index.tsx
  cli/src/registry/chat-thread/chat-thread.tsx
  cli/src/registry/chat-thread/config.json
  cli/src/registry/chat-thread/index.tsx
  cli/src/registry/config/globals.css
  cli/src/registry/config/tailwind.config.ts
  cli/src/registry/control-bar/config.json
  cli/src/registry/control-bar/control-bar.tsx
  cli/src/registry/control-bar/index.tsx
  cli/src/registry/form/config.json
  cli/src/registry/form/form.tsx
  cli/src/registry/form/index.tsx
  cli/src/registry/graph/config.json
  cli/src/registry/graph/graph.tsx
  cli/src/registry/graph/index.tsx
  cli/src/registry/input-fields/config.json
  cli/src/registry/input-fields/index.tsx
  cli/src/registry/input-fields/input-fields.tsx
  cli/src/registry/message-thread-collapsible/config.json
  cli/src/registry/message-thread-collapsible/index.tsx
  cli/src/registry/message-thread-collapsible/message-thread-collapsible.tsx
  cli/src/registry/message-thread-full/config.json
  cli/src/registry/message-thread-full/index.tsx
  cli/src/registry/message-thread-full/message-thread-full.tsx
  cli/src/registry/message-thread-panel/config.json
  cli/src/registry/message-thread-panel/index.tsx
  cli/src/registry/message-thread-panel/message-thread-panel.tsx
  cli/src/registry/message/config.json
  cli/src/registry/message/index.tsx
  cli/src/registry/message/message.tsx
  cli/src/registry/thread-list/config.json
  cli/src/registry/thread-list/index.tsx
  cli/src/registry/thread-list/thread-list.tsx
  cli/src/types/components.d.ts
  cli/src/types/utils.d.ts
  cli/tsconfig.json
  package-lock.json
  package.json
Labels: feat

#149 feat: send tool response in message content
  package-lock.json
  react-sdk/package.json
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: feat

#151 chore: bump babel for security fix
  package-lock.json
Labels: chore

#152 chore: remove some unused dependencies
  cli/package.json
  package-lock.json
  react-sdk/package.json
  showcase/package.json
Labels: chore

#148 chore(main): release react 0.15.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#153 chore(cli): update release configuration and CLI version to 0.0.3
  .github/workflows/release-please.yml
  .release-please-manifest.json
  cli/package.json
  release-please-config.json
Labels: chore

#154 chore(main): release tambo 0.1.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#156 chore(main): release tambo 0.1.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#157 fix: add explicit key= to work around subtle react caching behavior
  react-sdk/src/hooks/use-current-message.tsx
Labels: fix

#158 chore(main): release react 0.15.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#160 chore: show renderedComponent in Message component
  cli/src/registry/chat-thread/chat-thread.tsx
  cli/src/registry/message/message.tsx
  cli/src/types/components.d.ts
Labels: chore

#159 chore: pin stuff down to node >=20
  cli/package.json
  package-lock.json
  package.json
  react-sdk/package.json
  showcase/package.json
Labels: chore

#162 chore(main): release react 0.16.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#163 fix(cli): improve overall component ui
  cli/src/commands/add/tailwind.ts
  cli/src/registry/chat-input/chat-input.tsx
  cli/src/registry/chat-thread/chat-thread.tsx
  cli/src/registry/control-bar/config.json
  cli/src/registry/control-bar/control-bar.tsx
  cli/src/registry/control-bar/index.tsx
  cli/src/registry/message-thread-collapsible/config.json
  cli/src/registry/message-thread-collapsible/index.tsx
  cli/src/registry/message-thread-collapsible/message-thread-collapsible.tsx
  cli/src/registry/message-thread-full/config.json
  cli/src/registry/message-thread-full/index.tsx
  cli/src/registry/message-thread-full/message-thread-full.tsx
  cli/src/registry/message-thread-panel/config.json
  cli/src/registry/message-thread-panel/index.tsx
  cli/src/registry/message-thread-panel/message-thread-panel.tsx
  cli/src/registry/message/config.json
  cli/src/types/utils.d.ts
Labels: fix

#161 chore(main): release tambo 0.1.2
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#165 fix: only initialize component state value once
  react-sdk/src/hooks/use-component-state.tsx
Labels: fix

#166 chore(main): release react 0.16.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#170 fix: expose fetch param from switchthread
  package-lock.json
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#171 chore(main): release react 0.16.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#169 feat: add debounce, optimistic updates, and helper functions for prop updates
  package-lock.json
  react-sdk/package.json
  react-sdk/src/hooks/index.ts
  react-sdk/src/hooks/use-component-state.tsx
  react-sdk/src/hooks/use-streaming-props.tsx
  react-sdk/src/index.ts
Labels: feat

#167 chore(cli): update components UI and add update command
  cli/README.md
  cli/src/cli.ts
  cli/src/commands/add/component.ts
  cli/src/commands/add/types.ts
  cli/src/commands/init.ts
  cli/src/commands/update.ts
  cli/src/registry/chat-input/chat-input.tsx
  cli/src/registry/chat-input/config.json
  cli/src/registry/chat-input/index.tsx
  cli/src/registry/chat-thread/config.json
  cli/src/registry/chat-thread/index.tsx
  cli/src/registry/control-bar/config.json
  cli/src/registry/control-bar/control-bar.tsx
  cli/src/registry/input-fields/input-fields.tsx
  cli/src/registry/message-input/config.json
  cli/src/registry/message-input/index.tsx
  cli/src/registry/message-input/message-input.tsx
  cli/src/registry/message-suggestions.tsx/config.json
  cli/src/registry/message-suggestions.tsx/index.tsx
  cli/src/registry/message-suggestions.tsx/message-suggestions.tsx
  cli/src/registry/message-thread-collapsible/config.json
  cli/src/registry/message-thread-collapsible/message-thread-collapsible.tsx
  cli/src/registry/message-thread-full/config.json
  cli/src/registry/message-thread-full/message-thread-full.tsx
  cli/src/registry/message-thread-panel/config.json
  cli/src/registry/message-thread-panel/message-thread-panel.tsx
  cli/src/registry/message/config.json
  cli/src/registry/message/markdownComponents.tsx
  cli/src/registry/message/message.tsx
  cli/src/registry/thread-content/config.json
  cli/src/registry/thread-content/index.tsx
  cli/src/registry/thread-content/thread-content.tsx
  cli/src/registry/thread-history/config.json
  cli/src/registry/thread-history/index.tsx
  cli/src/registry/thread-history/thread-history.tsx
  cli/src/registry/thread-list/thread-list.tsx
  cli/src/types/components.d.ts
  cli/src/types/utils.d.ts
Labels: chore

#173 chore(main): release tambo 0.1.3
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#174 feat: add support for propsSchema
  .prettierrc
  react-sdk/README.md
  react-sdk/src/model/component-metadata.ts
  react-sdk/src/providers/tambo-registry-provider.tsx
  react-sdk/src/util/registry.ts
Labels: feat

#175 chore(main): release react 0.18.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#176 fix(cli): component path fix for message-suggestions
  cli/README.md
  cli/src/registry/message-suggestions/config.json
  cli/src/registry/message-suggestions/index.tsx
  cli/src/registry/message-suggestions/message-suggestions.tsx
Labels: fix

#177 chore(main): release tambo 0.1.4
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#188 fix: suggestions to filter for assistant
  react-sdk/src/hooks/use-suggestions.ts
Labels: fix

#190 chore(main): release tambo 0.1.5
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#123 chore(main): release showcase 0.1.4
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#196 chore: bump tambo/ts version
  package-lock.json
  react-sdk/package.json
Labels: chore

#197 chore(main): release react 0.18.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#198 fix(cli): add API key check; update component installation logic, update component UI
  cli/src/commands/add/component.ts
  cli/src/commands/add/index.ts
  cli/src/commands/add/types.ts
  cli/src/commands/init.ts
  cli/src/commands/update.ts
  cli/src/registry/message-input/message-input.tsx
  cli/src/registry/message-suggestions/config.json
  cli/src/registry/message-suggestions/message-generation-stage.tsx
  cli/src/registry/message-suggestions/message-suggestions.tsx
  cli/src/registry/message-suggestions/tooltip.tsx
  cli/src/registry/message-thread-full/message-thread-full.tsx
  cli/src/registry/message/message.tsx
  cli/src/registry/thread-content/thread-content.tsx
  cli/src/registry/thread-history/thread-history.tsx
  cli/src/types/components.d.ts
Labels: fix

#201 chore: allow switch to placeholder as 'new thread'
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: chore

#205 feat: add 'startNewThread' method
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: feat

#206 fix: lockfile
  package-lock.json
Labels: fix

#207 fix: add period to update release please
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#209 chore(deps): bump @tambo-ai/typescript-sdk from 0.39.0 to 0.40.0
  package-lock.json
  react-sdk/package.json
Labels: chore

#200 feat: useTamboThreads -> useTamboThreadList
  README.md
  cli/src/registry/thread-history/thread-history.tsx
  react-sdk/src/hooks/index.ts
  react-sdk/src/hooks/use-tambo-threads.ts
  react-sdk/src/index.ts
  showcase/src/components/ui/thread-history.tsx
Labels: feat

#211 chore: use npm install in ci workflow to work around version update bug
  .github/workflows/ci.yml
Labels: chore

#213 fix: allow for workspace version
  package-lock.json
  showcase/package.json
Labels: fix

#212 chore: allow manually running the release process
  .github/workflows/release-please.yml
Labels: chore

#203 chore(main): release react 0.19.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#202 refactor: use faster/pre-built isEqual, will be useful elsewhere
  package-lock.json
  react-sdk/package.json
  react-sdk/src/hooks/use-component-state.tsx
Labels: refactor

#215 docs: add JSDocs to exported functions
  package-lock.json
  react-sdk/eslint.config.mjs
  react-sdk/package.json
  react-sdk/src/hooks/react-query-hooks.ts
  react-sdk/src/hooks/use-component-state.tsx
  react-sdk/src/hooks/use-current-message.tsx
  react-sdk/src/hooks/use-streaming-props.tsx
  react-sdk/src/hooks/use-suggestions.ts
  react-sdk/src/hooks/use-tambo-threads.ts
  react-sdk/src/hooks/use-thread-input.ts
  react-sdk/src/model/component-metadata.ts
  react-sdk/src/model/generate-component-response.ts
  react-sdk/src/model/tambo-thread.ts
  react-sdk/src/model/validate-input.ts
  react-sdk/src/providers/tambo-provider.tsx
  react-sdk/src/providers/tambo-thread-provider.tsx
  react-sdk/src/util/generate-component.ts
  react-sdk/src/util/messages.ts
  react-sdk/src/util/query-utils.ts
Labels: docs

#216 docs: add even more jsdocs for public methods/hooks/etc
  react-sdk/eslint.config.mjs
  react-sdk/src/hooks/use-tambo-threads.ts
  react-sdk/src/index.ts
  react-sdk/src/providers/tambo-client-provider.tsx
  react-sdk/src/providers/tambo-component-provider.tsx
  react-sdk/src/providers/tambo-provider.tsx
  react-sdk/src/providers/tambo-registry-provider.tsx
  react-sdk/src/providers/tambo-thread-provider.tsx
  react-sdk/src/util/registry.ts
  react-sdk/src/util/tool-caller.ts
Labels: docs

#217 chore(deps): bump @tambo-ai/typescript-sdk to 0.41
  package-lock.json
  react-sdk/package.json
Labels: chore

#214 chore(main): release react 0.19.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#218 fix: remove currentState from dependency array in useTamboStreamingProps hook
  react-sdk/src/hooks/use-streaming-props.tsx
Labels: fix

#220 fix: update dependency array in useTamboStreamingProps to only include streamingProps
  react-sdk/src/hooks/use-streaming-props.tsx
Labels: fix

#219 chore(main): release react 0.19.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#221 fix: now the debounce just stores the current user value and doesn't sync back also made it 500ms default
  package-lock.json
  react-sdk/src/hooks/use-component-state.tsx
Labels: fix

#223 chore: bump typescript-sdk version to get componentState changes
  package-lock.json
  react-sdk/package.json
Labels: chore

#222 chore(main): release react 0.19.3
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#199 chore(main): release tambo 0.2.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#224 fix: do not debounce local updates
  react-sdk/src/hooks/use-component-state.tsx
Labels: fix

#225 chore(main): release react 0.19.4
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#237 fix: try using tsconfig paths to link to react package
  showcase/tsconfig.json
Labels: fix
