Repository tambo-ai/tambo, pull requests merged in 2025-04, with the labels that each got.

#238 fix: warn users if they are using old tambo cli
  cli/package.json
  cli/src/cli.ts
  package-lock.json
Labels: fix

#241 fix: show list of component if component is missing
  cli/package.json
  cli/src/cli.ts
  cli/src/commands/add/utils.ts
  cli/src/registry/control-bar/config.json
  cli/src/registry/form/config.json
  cli/src/registry/graph/config.json
  cli/src/registry/input-fields/config.json
  cli/src/registry/message-input/config.json
  cli/src/registry/message-suggestions/config.json
  cli/src/registry/message-thread-collapsible/config.json
  cli/src/registry/message-thread-full/config.json
  cli/src/registry/message-thread-panel/config.json
  cli/src/registry/message/config.json
  cli/src/registry/thread-content/config.json
  cli/src/registry/thread-history/config.json
  cli/src/registry/thread-list/config.json
  package-lock.json
Labels: fix

#204 chore: fix thread-history and updated showcase site
  cli/src/registry/form/form.tsx
  cli/src/registry/graph/graph.tsx
  cli/src/registry/thread-history/thread-history.tsx
  cli/src/types/utils.d.ts
  package-lock.json
  showcase/src/app/components-page/page.tsx
  showcase/src/app/layout.tsx
  showcase/src/app/template.tsx
  showcase/src/components/cli.tsx
  showcase/src/components/getting-started-steps.tsx
  showcase/src/components/second-navbar.tsx
  showcase/src/components/showcase-sections/ai-elements/chat-interfaces/FormChatInterface.tsx
  showcase/src/components/showcase-sections/ai-elements/chat-interfaces/GraphChatInterface.tsx
  showcase/src/components/showcase-sections/ai-elements/index.tsx
  showcase/src/components/ui/form.tsx
  showcase/src/components/ui/graph.tsx
  showcase/src/components/ui/message.tsx
  showcase/src/components/ui/thread-history.tsx
  showcase/src/constants/form-fields.ts
  showcase/src/constants/graph-data.ts
  showcase/src/providers/showcase-theme-provider.tsx
  showcase/src/styles/showcase-theme.css
  showcase/tailwind.config.ts
Labels: chore

#240 fix: warn about latest version, better src/ messaging
  cli/src/commands/init.ts
Labels: fix

#243 fix: workaround turbopack bugs w/Stainless shims
  react-sdk/src/providers/tambo-provider.tsx
Labels: fix

#242 fix: minor component cleanups: stop using useEffect/etc
  cli/src/registry/message-input/message-input.tsx
  cli/src/registry/message-suggestions/message-suggestions.tsx
  cli/src/registry/message-thread-collapsible/message-thread-collapsible.tsx
  cli/src/registry/thread-history/thread-history.tsx
  react-sdk/src/providers/tambo-client-provider.tsx
  showcase/src/components/ui/message-input.tsx
  showcase/src/components/ui/message-suggestions.tsx
  showcase/src/components/ui/thread-history.tsx
Labels: fix

#236 chore(main): release react 0.19.5
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#245 docs: update README with enhanced usage examples and component registration instructions for Tambo AI
  README.md
Labels: docs

#248 fix: more mac kbd cleanup: quiet down hydration warnings
  cli/src/registry/message-input/message-input.tsx
  cli/src/registry/message-suggestions/message-suggestions.tsx
  cli/src/registry/message-thread-collapsible/message-thread-collapsible.tsx
  cli/src/registry/thread-history/thread-history.tsx
  showcase/src/components/ui/message-input.tsx
  showcase/src/components/ui/message-suggestions.tsx
  showcase/src/components/ui/message-thread-collapsible.tsx
  showcase/src/components/ui/thread-history.tsx
Labels: fix

#246 fix: Remove many uses of currentThreadId
  package-lock.json
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#250 chore(main): release react 0.19.6
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#251 docs: update README files for React SDK and CLI, fix links and enhance installation instructions
  README.md
  cli/README.md
  react-sdk/README.md
  showcase/README.md
Labels: docs

#247 fix: improved CLI commands with user feedback and component location handling
  cli/src/commands/add/component.ts
  cli/src/commands/add/tailwind.ts
  cli/src/commands/init.ts
  cli/src/commands/update.ts
  cli/src/registry/control-bar/control-bar.tsx
  cli/src/types/utils.d.ts
Labels: fix

#244 chore(main): release tambo 0.2.2
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#252 chore(main): release react 0.19.7
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#210 chore(main): release showcase 0.3.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#253 docs: add a bunch of jsdocs for components
  cli/src/registry/control-bar/control-bar.tsx
  cli/src/registry/form/form.tsx
  cli/src/registry/graph/graph.tsx
  cli/src/registry/input-fields/input-fields.tsx
  cli/src/registry/message-input/message-input.tsx
  cli/src/registry/message-suggestions/message-suggestions.tsx
  cli/src/registry/message-thread-collapsible/message-thread-collapsible.tsx
  cli/src/registry/message-thread-full/message-thread-full.tsx
  cli/src/registry/message-thread-panel/message-thread-panel.tsx
  cli/src/registry/message/message.tsx
  cli/src/registry/thread-content/thread-content.tsx
  cli/src/registry/thread-history/thread-history.tsx
  cli/src/registry/thread-list/thread-list.tsx
Labels: docs

#254 fix: only run npm install twice
  cli/src/commands/add/component.ts
  cli/src/commands/add/index.ts
  cli/src/commands/update.ts
Labels: fix

#257 feat: add tambo.ts for registering components & simplify code
  cli/README.md
  cli/src/commands/init.ts
  cli/src/templates/tambo-template.ts
Labels: feat

#256 feat(cli): add 'create-tambo-app' command to CLI for app creation from template
  cli/src/cli.ts
  cli/src/commands/create-app.ts
Labels: feat

#255 chore(main): release tambo 0.3.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#260 fix(cli): add displayName to MessageSuggestions and ThreadHistory components
  cli/src/registry/message-suggestions/message-suggestions.tsx
  cli/src/registry/thread-history/thread-history.tsx
Labels: fix

#261 chore(main): release tambo 0.3.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#263 chore(cli): change the appname in package.json while installing template
  cli/src/cli.ts
  cli/src/commands/create-app.ts
Labels: chore

#265 fix(showcase): enable client-side rendering in AI elements section
  showcase/src/components/showcase-sections/ai-elements/index.tsx
Labels: fix

#268 fix(showcase): handle not found page rendering in template component
  showcase/src/app/not-found.tsx
  showcase/src/app/template.tsx
Labels: fix

#266 chore(main): release showcase 0.3.1
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#269 refactor(cli): remove tambo.ts from init command (only full-send)
  cli/src/commands/init.ts
Labels: refactor

#271 fix: Don't throw error if TamboProvider used outside browser
  react-sdk/src/providers/tambo-provider.tsx
Labels: fix

#272 chore(main): release react 0.19.8
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#273 fix(cli): add --init-git flag to create-app command and fix message-input auto-focus
  cli/src/cli.ts
  cli/src/commands/create-app.ts
  cli/src/registry/message-input/message-input.tsx
Labels: fix

#270 chore(main): release tambo 0.3.3
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#267 chore: add create-tambo-app package and release configurations
  .github/workflows/release-please.yml
  .release-please-manifest.json
  create-tambo-app/README.md
  create-tambo-app/eslint.config.mjs
  create-tambo-app/package.json
  create-tambo-app/src/index.ts
  create-tambo-app/tsconfig.json
  package-lock.json
  package.json
  release-please-config.json
Labels: chore

#274 chore(main): release create-tambo-app 0.0.3
  .release-please-manifest.json
  create-tambo-app/CHANGELOG.md
  create-tambo-app/package.json
Labels: chore, autorelease: pending

#275 chore: update readme with new quickstart command
  README.md
Labels: chore

#276 feat: enforce zod/json-ness of propSchema prop
  react-sdk/src/model/component-metadata.ts
  react-sdk/src/providers/tambo-registry-provider.tsx
Labels: feat

#277 chore(main): release react 0.20.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#292 fix: make threadId optional in sendThreadMessage
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#293 chore(main): release react 0.20.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#295 fix: force typescript-sdk to be the right version
  package-lock.json
  react-sdk/src/providers/tambo-provider.tsx
Labels: fix

#296 chore(main): release react 0.20.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#294 test: enable tests in builds, fix suggestions test
  .github/workflows/ci.yml
  package-lock.json
  react-sdk/jest.config.ts
  react-sdk/package.json
  react-sdk/src/hooks/__tests__/use-suggestions.test.tsx
Labels: test

#291 feat(showcase): re-design of showcase fixed TAM-51
  showcase/src/app/components-page/page.tsx
  showcase/src/app/components/(blocks)/message-thread-collapsible/page.tsx
  showcase/src/app/components/(blocks)/message-thread-full/page.tsx
  showcase/src/app/components/(blocks)/message-thread-panel/page.tsx
  showcase/src/app/components/(generative)/form/page.tsx
  showcase/src/app/components/(generative)/graph/page.tsx
  showcase/src/app/components/layout.tsx
  showcase/src/app/get-started/page.tsx
  showcase/src/app/layout.tsx
  showcase/src/app/page.tsx
  showcase/src/app/template.tsx
  showcase/src/components/cli.tsx
  showcase/src/components/footer.tsx
  showcase/src/components/generative/FormChatInterface.tsx
  showcase/src/components/generative/GraphChatInterface.tsx
  showcase/src/components/getting-started-steps.tsx
  showcase/src/components/navbar.tsx
  showcase/src/components/second-navbar.tsx
  showcase/src/components/showcase-section.tsx
  showcase/src/components/showcase-sections/ai-elements/index.tsx
  showcase/src/components/showcase-sections/messaging-interfaces.tsx
  showcase/src/components/sidebar.tsx
  showcase/src/components/tab-content.tsx
  showcase/src/components/tabbed-section.tsx
  showcase/src/components/ui/doc-components.tsx
  showcase/src/components/ui/tabs.tsx
  showcase/src/constants/steps.ts
  showcase/src/lib/navigation.ts
  showcase/src/providers/mobile-provider.tsx
  showcase/src/types/showcase.ts
  showcase/src/types/tabs.ts
Labels: feat

#298 test: start wiring up hook tests
  package-lock.json
  react-sdk/jest.config.ts
  react-sdk/package.json
  react-sdk/src/hooks/__tests__/use-suggestions.test.tsx
  react-sdk/src/hooks/__tests__/use-tambo-threads.test.tsx
  react-sdk/src/hooks/react-query-hooks.ts
  react-sdk/src/hooks/use-suggestions.ts
  react-sdk/src/hooks/use-tambo-threads.ts
  react-sdk/src/providers/tambo-provider.tsx
  react-sdk/src/setupTests.ts
  react-sdk/src/testing/types.ts
Labels: test

#290 chore(main): release showcase 0.4.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#299 test: add some basic tests for the thread provider
  react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
  react-sdk/src/providers/tambo-registry-provider.tsx
  react-sdk/src/testing/tools.ts
Labels: test

#303 chore(main): release showcase 0.4.1
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#306 feat(cli): update message-input component style
  cli/src/registry/message-input/message-input.tsx
Labels: feat

#289 chore(main): release tambo 0.4.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#309 chore(main): release tambo 0.5.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#325 chore: update dependabot groups
  .github/dependabot.yml
Labels: chore

#297 chore(main): release react 0.20.3
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#340 fix: Show toolcall message in thread
  react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#341 chore(main): release react 0.20.4
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#344 feat: send all defined tools, even if they are not associated with a component
  package-lock.json
  react-sdk/package.json
  react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
  react-sdk/src/providers/tambo-thread-provider.tsx
  react-sdk/src/util/registry.ts
Labels: feat

#342 chore(main): release react 0.21.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#351 chore(main): release react 0.21.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#352 fix: Add `tools=` prop to register tools in provider
  react-sdk/src/providers/tambo-provider.tsx
  react-sdk/src/providers/tambo-registry-provider.tsx
Labels: fix

#354 docs: add a readme update to trigger a build'
  README.md
Labels: docs

#356 fix: make sure to show each streamed message, even if new ones come in on the same stream
  react-sdk/src/hooks/use-suggestions.ts
  react-sdk/src/providers/tambo-thread-provider.tsx
Labels: fix

#357 chore(main): release react 0.21.3
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#355 chore: fix errant backticks
  README.md
Labels: chore

#358 chore(deps): manually bump typescript-sdk
  package-lock.json
  react-sdk/package.json
  react-sdk/src/hooks/__tests__/use-tambo-threads.test.tsx
  react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
Labels: chore

#360 chore(deps): bump typescript-sdk to get status messages
  package-lock.json
  react-sdk/package.json
Labels: chore

#359 chore(main): release react 0.21.4
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#343 refactor(UI): update UI components and styles for improved usability and integration
  cli/src/commands/add/component.ts
  cli/src/commands/add/tailwind.ts
  cli/src/registry/canvas-space/canvas-space.tsx
  cli/src/registry/canvas-space/config.json
  cli/src/registry/canvas-space/index.tsx
  cli/src/registry/config/globals.css
  cli/src/registry/config/tailwind.config.ts
  cli/src/registry/control-bar/config.json
  cli/src/registry/control-bar/control-bar.tsx
  cli/src/registry/graph/graph.tsx
  cli/src/registry/lib/thread-hooks.ts
  cli/src/registry/message-input/index.tsx
  cli/src/registry/message-input/message-input.tsx
  cli/src/registry/message-suggestions/index.tsx
  cli/src/registry/message-suggestions/message-suggestions.tsx
  cli/src/registry/message-suggestions/tooltip.tsx
  cli/src/registry/message-thread-collapsible/config.json
  cli/src/registry/message-thread-collapsible/message-thread-collapsible.tsx
  cli/src/registry/message-thread-full/config.json
  cli/src/registry/message-thread-full/message-thread-full.tsx
  cli/src/registry/message-thread-panel/config.json
  cli/src/registry/message-thread-panel/message-thread-panel.tsx
  cli/src/registry/message/config.json
  cli/src/registry/message/index.tsx
  cli/src/registry/message/markdownComponents.tsx
  cli/src/registry/message/message.tsx
  cli/src/registry/scrollable-message-container/config.json
  cli/src/registry/scrollable-message-container/index.tsx
  cli/src/registry/scrollable-message-container/scrollable-message-container.tsx
  cli/src/registry/thread-content/index.tsx
  cli/src/registry/thread-content/thread-content.tsx
  cli/src/registry/thread-dropdown/config.json
  cli/src/registry/thread-dropdown/index.tsx
  cli/src/registry/thread-dropdown/thread-dropdown.tsx
  cli/src/registry/thread-history/index.tsx
  cli/src/registry/thread-history/thread-history.tsx
  cli/src/registry/thread-list/config.json
  cli/src/registry/thread-list/index.tsx
  cli/src/registry/thread-list/thread-list.tsx
  cli/src/types/components.d.ts
  cli/src/types/utils.d.ts
Labels: refactor

#321 chore(main): release tambo 0.5.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#320 chore(main): release showcase 0.4.2
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#288 chore(main): release create-tambo-app 0.0.4
  .release-please-manifest.json
  create-tambo-app/CHANGELOG.md
  create-tambo-app/package.json
Labels: chore, autorelease: pending
