Repository tambo-ai/tambo, pull requests merged in 2025-05, with the labels that each got.

#361 feat(UI): add loading indicator and tool status messages to message component
  cli/src/registry/message-thread-full/config.json
  cli/src/registry/message-thread-full/message-thread-full.tsx
  cli/src/registry/message-thread-full/thread-container.tsx
  cli/src/registry/message/message.tsx
  cli/src/types/components.d.ts
  package-lock.json
Labels: feat

#363 fix: get threadId from other hooks
  react-sdk/src/hooks/use-component-state.tsx
  react-sdk/src/hooks/use-current-message.tsx
Labels: fix

#362 chore(main): release tambo 0.6.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: chore, autorelease: pending

#379 feat: allow env to override tambo URL, for local dev
  cli/src/commands/init.ts
Labels: feat

#377 chore(main): release create-tambo-app 0.1.0
  .release-please-manifest.json
  create-tambo-app/CHANGELOG.md
  create-tambo-app/package.json
Labels: chore, autorelease: pending

#366 chore(main): release showcase 0.5.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#382 refactor: replace hardcoded context keys with useUserContextKey in message thread components
  showcase/src/app/components/(blocks)/message-thread-collapsible/page.tsx
  showcase/src/app/components/(blocks)/message-thread-full/page.tsx
  showcase/src/app/components/(blocks)/message-thread-panel/page.tsx
  showcase/src/app/page.tsx
  showcase/src/components/generative/CanvasChatInterface.tsx
  showcase/src/components/generative/FormChatInterface.tsx
  showcase/src/components/generative/GraphChatInterface.tsx
  showcase/src/lib/useUserContextKey.ts
Labels: refactor

#384 chore(main): release showcase 0.5.1
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#385 chore: update GitHub Actions permissions for PR title validation
  .github/workflows/conventional-commits.yml
Labels: chore

#386 fix: sidebar and message input resizing issues
  showcase/src/app/components/(blocks)/message-thread-full/page.tsx
  showcase/src/app/page.tsx
  showcase/src/components/generative/FormChatInterface.tsx
  showcase/src/components/generative/GraphChatInterface.tsx
Labels: fix

#387 chore(main): release showcase 0.5.2
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#388 feat: add full-screen button to demos
  package-lock.json
  showcase/package.json
  showcase/src/app/components/(blocks)/message-thread-collapsible/page.tsx
  showcase/src/app/components/(blocks)/message-thread-full/page.tsx
  showcase/src/app/components/(blocks)/message-thread-panel/page.tsx
  showcase/src/app/components/(canvas)/canvas-space/page.tsx
  showcase/src/app/components/(generative)/form/page.tsx
  showcase/src/app/components/(generative)/graph/page.tsx
  showcase/src/app/components/demo-wrapper.tsx
  showcase/src/app/page.tsx
  showcase/src/components/ui/button.tsx
  showcase/src/components/ui/dialog.tsx
  showcase/src/components/ui/visually-hidden.tsx
Labels: feat

#389 chore(main): release showcase 0.6.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: chore, autorelease: pending

#383 feat: add support for browser-visible MCP servers
  package-lock.json
  react-sdk/package.json
  react-sdk/src/index.ts
  react-sdk/src/model/component-metadata.ts
  react-sdk/src/providers/tambo-mcp-provider.tsx
  react-sdk/src/testing/tools.ts
  react-sdk/src/util/mcp-client.ts
  react-sdk/src/util/mcp-tools-client.ts
  react-sdk/src/util/registry.ts
Labels: feat

#390 chore(main): release react 0.23.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#391 refactor: move MCP into separate import (@tambo-ai/react/mcp)
  react-sdk/package.json
  react-sdk/src/index.ts
  react-sdk/src/mcp/index.ts
  react-sdk/src/mcp/mcp-client.ts
  react-sdk/src/mcp/mcp-tools-client.ts
  react-sdk/src/mcp/tambo-mcp-provider.tsx
Labels: refactor

#392 chore(main): release react 0.23.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: chore, autorelease: pending

#416 chore(main): release create-tambo-app 0.1.1
  .release-please-manifest.json
  create-tambo-app/CHANGELOG.md
  create-tambo-app/package.json
Labels: autorelease: pending

#414 chore(main): release tambo 0.9.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#413 chore(main): release showcase 0.7.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#415 chore(main): release react 0.23.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#418 chore(main): release react 0.24.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#422 chore(main): release react 0.25.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#423 chore(main): release react 0.25.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#421 chore(main): release tambo 0.10.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: tagged

#424 chore(main): release react 0.26.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: tagged

#438 chore(main): release create-tambo-app 0.1.2
  .release-please-manifest.json
  create-tambo-app/CHANGELOG.md
  create-tambo-app/package.json
Labels: autorelease: pending

#437 chore(main): release tambo 0.10.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#446 chore(main): release create-tambo-app 0.1.4
  .release-please-manifest.json
  create-tambo-app/CHANGELOG.md
  create-tambo-app/package.json
Labels: autorelease: pending

#465 chore(main): release react 0.26.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#467 chore(main): release react 0.26.3
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#448 chore(main): release tambo 0.11.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#426 chore(main): release showcase 0.8.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#474 chore(main): release tambo 0.11.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#470 chore(main): release react 0.26.4
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#477 chore(main): release tambo 0.12.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#479 chore(main): release showcase 0.8.1
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#482 chore(main): release react 0.27.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#487 chore(main): release react 0.28.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#483 chore(main): release tambo 0.13.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#484 chore(main): release showcase 0.8.2
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#489 chore(main): release tambo 0.13.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending
