Repository tambo-ai/tambo, pull requests merged in 2025-08, with the labels that each got.

#748 chore(main): release docs 1.0.7
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#753 chore(main): release docs 1.0.8
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#756 chore(main): release docs 1.0.9
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#761 chore(main): release react 0.41.2
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#764 chore(main): release docs 1.0.10
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#766 chore(main): release docs 1.0.11
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#768 chore(main): release docs 1.0.12
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#772 chore(main): release showcase 0.17.1
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#771 chore(main): release tambo 0.26.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#773 chore(main): release showcase 0.18.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#794 chore(main): release react 0.42.1
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#795 chore(main): release docs 1.1.2
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#803 chore(main): release docs 1.2.0
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#800 chore(main): release react 0.43.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#791 chore(main): release tambo 0.27.1
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#815 chore(main): release docs 1.2.1
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#814 chore(main): release tambo 0.27.2
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending

#812 chore(main): release create-tambo-app 0.1.11
  .release-please-manifest.json
  create-tambo-app/CHANGELOG.md
  create-tambo-app/package.json
Labels: autorelease: pending

#811 chore(main): release showcase 0.18.2
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#832 chore(main): release docs 1.2.2
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#819 chore(main): release react 0.44.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#818 chore(main): release showcase 0.18.3
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#842 docs: add announcement banner for open-sourced backend and TamboHack
  README.md
Labels: codex

#869 chore(main): release react 0.45.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#838 docs: add docs header and chatwithtambo
  docs/package.json
  docs/public/logo/icon/Octo-Icon.png
  docs/public/logo/icon/Octo-Icon.svg
  docs/src/app/(docs)/[[...slug]]/page.tsx
  docs/src/app/(docs)/layout.tsx
  docs/src/app/(docs)/styles.css
  docs/src/app/api/github-stars/route.ts
  docs/src/app/global.css
  docs/src/app/layout.config.tsx
  docs/src/app/layout.tsx
  docs/src/components/animated-counter.tsx
  docs/src/components/dashboard-card.tsx
  docs/src/components/discord-invite.tsx
  docs/src/components/github-issue-creator.tsx
  docs/src/components/header-bar.tsx
  docs/src/components/header-search.tsx
  docs/src/components/tambo/markdown-components.tsx
  docs/src/components/tambo/mcp-config-modal.tsx
  docs/src/components/tambo/message-generation-stage.tsx
  docs/src/components/tambo/message-input.tsx
  docs/src/components/tambo/message-suggestions.tsx
  docs/src/components/tambo/message-thread-collapsible.tsx
  docs/src/components/tambo/message.tsx
  docs/src/components/tambo/scrollable-message-container.tsx
  docs/src/components/tambo/suggestions-tooltip.tsx
  docs/src/components/tambo/thread-content.tsx
  docs/src/components/tambo/thread-dropdown.tsx
  docs/src/lib/tambo.ts
  docs/src/lib/thread-hooks.ts
  docs/src/lib/utils.ts
  package-lock.json
  react-sdk/CHANGELOG.md
  react-sdk/src/hooks/use-thread-input.ts
Labels: feat, docs

#858 chore(main): release docs 1.2.3
  .release-please-manifest.json
  docs/CHANGELOG.md
  docs/package.json
Labels: autorelease: pending

#859 chore(main): release showcase 0.19.0
  .release-please-manifest.json
  showcase/CHANGELOG.md
  showcase/package.json
Labels: autorelease: pending

#870 chore(main): release react 0.46.0
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#911 chore(main): release react 0.46.3
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#926 chore(main): release react 0.46.4
  .release-please-manifest.json
  react-sdk/CHANGELOG.md
  react-sdk/package.json
Labels: autorelease: pending

#910 chore(main): release tambo 0.30.0
  .release-please-manifest.json
  cli/CHANGELOG.md
  cli/package.json
Labels: autorelease: pending
